// Glosario de términos jurídicos y quizzes de autoevaluación.
// Contenido original, educativo, complementario a content.js.

const GLOSARIO = [
  { termino: "Acción de tutela", definicion: "Mecanismo judicial rápido (máximo 10 días hábiles) para proteger un derecho fundamental que está siendo vulnerado o amenazado. Cualquier persona puede presentarla, sin abogado, ante cualquier juez." },
  { termino: "Habeas corpus", definicion: "Mecanismo que protege exclusivamente la libertad personal frente a una privación ilegal. Debe resolverse en máximo 36 horas." },
  { termino: "Habeas data", definicion: "Derecho a conocer, actualizar y rectificar la información que las entidades tienen sobre ti, especialmente en bases de datos personales y financieras." },
  { termino: "Exequátur", definicion: "Trámite ante la Corte Suprema de Justicia para que una sentencia dictada en otro país tenga efectos legales en Colombia (por ejemplo, un divorcio decretado en el exterior)." },
  { termino: "Prescripción", definicion: "Pérdida de la posibilidad de exigir judicialmente un derecho por el simple paso del tiempo sin ejercerlo. A diferencia de la caducidad, puede interrumpirse o suspenderse." },
  { termino: "Caducidad", definicion: "Extinción de una acción o derecho por vencimiento de un plazo legal fijo, que corre de forma objetiva y no admite interrupción ni suspensión." },
  { termino: "Jurisprudencia", definicion: "Conjunto de decisiones judiciales sobre un mismo tema, especialmente de las altas cortes, que sirven para interpretar y aplicar el derecho de forma consistente." },
  { termino: "Doctrina", definicion: "Opiniones y análisis de juristas y académicos sobre el derecho. Es una fuente auxiliar: orienta la interpretación, pero no es obligatoria como la ley o la jurisprudencia vinculante." },
  { termino: "Ratio decidendi", definicion: "La razón central y vinculante de una sentencia: el argumento que efectivamente sustenta la decisión, y por eso sirve como precedente para casos futuros similares." },
  { termino: "Obiter dictum", definicion: "Consideraciones adicionales que un juez incluye en una sentencia pero que no fueron determinantes para la decisión. No son vinculantes como precedente." },
  { termino: "Precedente judicial", definicion: "La sentencia (o línea de sentencias) que un juez debe seguir al resolver un caso similar, salvo que exponga razones suficientes para apartarse de ella." },
  { termino: "Debido proceso", definicion: "Derecho fundamental a que cualquier actuación judicial o administrativa en tu contra siga las reglas y garantías previamente establecidas: ser oído, presentar pruebas, conocer los cargos, entre otras." },
  { termino: "Presunción de inocencia", definicion: "Principio según el cual toda persona se considera inocente hasta que se demuestre lo contrario mediante un juicio con las garantías del debido proceso." },
  { termino: "Cosa juzgada", definicion: "Efecto de una sentencia en firme que impide volver a litigar sobre el mismo asunto entre las mismas partes: el caso queda definitivamente resuelto." },
  { termino: "Título ejecutivo", definicion: "Documento que contiene una obligación clara, expresa y actualmente exigible (como un pagaré o una factura), que permite iniciar directamente un proceso ejecutivo de cobro." },
  { termino: "Mérito ejecutivo", definicion: "Cualidad que tiene un documento (como un acta de conciliación) de poder exigirse directamente por la vía ejecutiva, sin necesidad de un juicio declarativo previo." },
  { termino: "Excepción de inconstitucionalidad", definicion: "Facultad de cualquier juez o autoridad de inaplicar, en un caso concreto, una norma que considere claramente contraria a la Constitución." },
  { termino: "Control de constitucionalidad", definicion: "Mecanismo mediante el cual la Corte Constitucional revisa si una ley o norma es compatible con la Constitución, y puede declararla inexequible (inválida)." },
  { termino: "Bloque de constitucionalidad", definicion: "Conjunto de normas que, sin estar escritas en el texto de la Constitución, tienen su misma jerarquía — como ciertos tratados de derechos humanos." },
  { termino: "Sentencia de unificación (SU)", definicion: "Sentencia de la Corte Constitucional que unifica criterios sobre un tema donde existían decisiones distintas, fijando la interpretación que deben seguir los demás jueces." },
  { termino: "Acto administrativo", definicion: "Decisión de una entidad pública que crea, modifica o extingue una situación jurídica — por ejemplo, otorgar o negar una licencia." },
  { termino: "Silencio administrativo", definicion: "Efecto legal que se produce cuando una entidad no responde una solicitud dentro del plazo: en algunos casos se entiende negada, y en otros, concedida a favor del ciudadano." },
  { termino: "Derecho de petición", definicion: "Derecho fundamental a presentar solicitudes respetuosas ante cualquier autoridad y recibir una respuesta de fondo, generalmente en 15 días hábiles." },
  { termino: "Personería jurídica", definicion: "Reconocimiento legal que le da a una organización (empresa, fundación, partido) capacidad para tener derechos y obligaciones propias, distintas de las de sus miembros." },
  { termino: "Persona natural / persona jurídica", definicion: "Persona natural es cualquier ser humano. Persona jurídica es una entidad (empresa, fundación) a la que la ley le reconoce capacidad de tener derechos y obligaciones, distinta de sus miembros." },
  { termino: "Dolo", definicion: "Intención de causar un daño o de engañar a otra persona. Es el grado más alto de responsabilidad: actuar sabiendo y queriendo el resultado dañoso." },
  { termino: "Culpa", definicion: "Negligencia, descuido o falta de cuidado que causa un daño, sin intención de causarlo. Es distinta del dolo, que sí implica intención." },
  { termino: "Nexo causal", definicion: "La relación de causa y efecto que debe existir entre una conducta y un daño para que exista responsabilidad: probar que ese daño específico fue consecuencia de esa conducta." },
  { termino: "Responsabilidad solidaria", definicion: "Cuando varias personas responden completamente por una misma deuda u obligación: el acreedor puede cobrarle el total a cualquiera de ellas, no solo una parte proporcional." },
  { termino: "Escritura pública", definicion: "Documento autorizado por un notario que da fe de un acto o contrato (como una compraventa de inmueble), con fuerza probatoria especial." },
  { termino: "Oponibilidad", definicion: "Cualidad de un acto (generalmente tras su registro público) de producir efectos frente a terceros, no solo entre quienes lo firmaron." },
  { termino: "Patrimonio autónomo", definicion: "Conjunto de bienes que, en una fiducia, se separan legalmente tanto del patrimonio de quien los entrega como del de quien los administra, protegiéndolos de los acreedores de ambos." },
  { termino: "Levantamiento del velo corporativo", definicion: "Figura excepcional que permite hacer responsable directamente a los socios o a la matriz de una sociedad, ignorando su personalidad jurídica separada, cuando se prueba fraude o abuso." },
  { termino: "Interés superior del menor", definicion: "Principio que exige que toda decisión que afecte a un niño, niña o adolescente priorice su bienestar por encima de cualquier otro interés, incluido el de sus padres." },
  { termino: "Sana crítica", definicion: "Sistema de valoración de pruebas donde el juez decide libremente pero debe motivar su decisión con base en la lógica, la ciencia y la experiencia, no de forma arbitraria." },
  { termino: "Carga de la prueba", definicion: "Regla que determina a quién le corresponde probar un hecho en un proceso. Por lo general, quien afirma algo debe probarlo." },
  { termino: "Cadena de custodia", definicion: "Registro documentado de cada persona que tuvo contacto con una prueba, desde que se recolecta hasta que se presenta en juicio, para garantizar que no fue alterada." },
  { termino: "Recurso de apelación", definicion: "Petición para que un juez o tribunal superior revise una decisión, pudiendo confirmarla, modificarla o revocarla." },
  { termino: "Recurso de casación", definicion: "Recurso extraordinario ante una alta corte que corrige errores graves de derecho en una sentencia, sin volver a juzgar los hechos del caso." },
  { termino: "Recurso de reposición", definicion: "Petición para que la misma autoridad que tomó una decisión la reconsidere, antes de acudir a una instancia superior." },
  { termino: "Medida cautelar", definicion: "Decisión provisional de un juez para proteger el resultado de un proceso mientras este se resuelve — como un embargo preventivo." },
  { termino: "Conciliación", definicion: "Mecanismo donde un tercero neutral ayuda a las partes a llegar a un acuerdo, sin imponerles una decisión." },
  { termino: "Arbitraje", definicion: "Mecanismo donde un árbitro (o tribunal de árbitros) resuelve un conflicto con la misma fuerza que un juez, con base en un pacto arbitral previo entre las partes." },
  { termino: "Laudo arbitral", definicion: "La decisión final de un tribunal de arbitraje, equivalente a una sentencia judicial, solo impugnable mediante el recurso de anulación por causales procesales taxativas." },
];

const QUIZZES = {
  principiante: [
    {
      pregunta: "¿Cuál norma está por encima de todas las demás en Colombia?",
      opciones: ["El Código Civil", "La Constitución Política", "Un decreto presidencial", "Un acuerdo municipal"],
      correcta: 1,
      explicacion: "La Constitución es la norma de normas: ninguna ley, decreto o contrato puede contradecirla.",
    },
    {
      pregunta: "¿Qué mecanismo protege un derecho fundamental amenazado, en máximo 10 días?",
      opciones: ["La acción de tutela", "El recurso de casación", "El exequátur", "La conciliación"],
      correcta: 0,
      explicacion: "La acción de tutela es rápida, no necesita abogado y protege derechos fundamentales.",
    },
    {
      pregunta: "¿Cuántas ramas del poder público hay en Colombia?",
      opciones: ["Dos", "Tres", "Cuatro", "Cinco"],
      correcta: 1,
      explicacion: "Legislativa, Ejecutiva y Judicial, que se controlan entre sí.",
    },
    {
      pregunta: "¿Qué prefijo identifica una sentencia de tutela de la Corte Constitucional?",
      opciones: ["C-", "SU-", "T-", "A-"],
      correcta: 2,
      explicacion: "T- es tutela, C- es constitucionalidad, SU- es unificación.",
    },
    {
      pregunta: "¿Es obligatorio que un contrato esté siempre por escrito para ser válido?",
      opciones: ["Sí, siempre", "No, muchos son válidos verbalmente, aunque escribirlos es recomendable", "Solo si supera un salario mínimo", "Solo entre empresas"],
      correcta: 1,
      explicacion: "No todos los contratos exigen forma escrita, aunque dejarlo por escrito facilita probarlo después.",
    },
    {
      pregunta: "¿A dónde puedes acudir para asesoría legal gratuita como estudiante o persona de bajos recursos?",
      opciones: ["Solo a un abogado particular", "A un consultorio jurídico universitario o una Casa de Justicia", "No existe esa opción en Colombia", "Solo a la Fiscalía"],
      correcta: 1,
      explicacion: "Los consultorios jurídicos universitarios y las Casas de Justicia ofrecen orientación gratuita.",
    },
  ],
  intermedio: [
    {
      pregunta: "¿Qué elementos configuran un contrato de trabajo, sin importar el nombre que le den las partes?",
      opciones: ["Solo el pago de un salario", "Prestación personal, subordinación y remuneración", "Un contrato firmado ante notario", "Trabajar más de 8 horas al día"],
      correcta: 1,
      explicacion: "Si hay esos tres elementos, existe un contrato de trabajo real sin importar cómo se llame.",
    },
    {
      pregunta: "¿Ante quién puede tramitarse un divorcio de mutuo acuerdo sin hijos menores?",
      opciones: ["Solo ante un juez", "Ante notario", "Ante la Policía", "Ante el Congreso"],
      correcta: 1,
      explicacion: "Sin hijos menores y con mutuo acuerdo, el divorcio puede hacerse ante notario, más rápido que un proceso judicial.",
    },
    {
      pregunta: "¿Qué debe probar la Fiscalía para que alguien sea condenado penalmente?",
      opciones: ["Nada, basta la denuncia", "Que la conducta fue típica, antijurídica y culpable, más allá de duda razonable", "Solo que hubo un daño", "Que el acusado no tiene abogado"],
      correcta: 1,
      explicacion: "El sistema acusatorio exige a la Fiscalía probar los tres elementos del delito, respetando la presunción de inocencia.",
    },
    {
      pregunta: "¿Qué sociedad es hoy la más usada en Colombia por su flexibilidad?",
      opciones: ["La Sociedad Anónima (S.A.)", "La Sociedad por Acciones Simplificada (SAS)", "La Sociedad Colectiva", "La Sociedad de Hecho"],
      correcta: 1,
      explicacion: "La SAS permite constituirse con un solo accionista y por documento privado, mucho más ágil que otros tipos.",
    },
    {
      pregunta: "¿Cuánto tiempo tiene una entidad pública para responder un derecho de petición general?",
      opciones: ["48 horas", "15 días hábiles, en general", "6 meses", "No hay plazo legal"],
      correcta: 1,
      explicacion: "15 días hábiles es el plazo general; 10 para consultas y 3 para solicitudes de documentos.",
    },
    {
      pregunta: "¿Qué garantiza el SOAT en un accidente de tránsito?",
      opciones: ["Solo cubre al conductor si no tuvo la culpa", "Cubre gastos médicos y funerarios de las víctimas, sin importar de quién fue la culpa", "Solo cubre daños al vehículo", "Es opcional en Colombia"],
      correcta: 1,
      explicacion: "El SOAT es de carácter social: cubre a las víctimas, incluido el conductor causante, sin importar la culpa.",
    },
  ],
  experto: [
    {
      pregunta: "¿Qué distingue al control difuso (excepción de inconstitucionalidad) del control concentrado en Colombia?",
      opciones: ["No existen ambos en Colombia", "El difuso lo ejerce cualquier juez en un caso concreto; el concentrado solo la Corte Constitucional con efectos generales", "Son exactamente lo mismo", "El difuso solo aplica a tratados internacionales"],
      correcta: 1,
      explicacion: "Colombia combina ambos modelos: control concentrado (Corte Constitucional) y difuso (cualquier juez, caso a caso).",
    },
    {
      pregunta: "¿Qué exige la responsabilidad del Estado bajo el artículo 90 de la Constitución?",
      opciones: ["Que la conducta del Estado haya sido ilegal", "Un daño antijurídico imputable a una autoridad, aunque la conducta no fuera ilegal", "Solo aplica a daños causados por la Policía", "Que exista una condena penal previa"],
      correcta: 1,
      explicacion: "'Antijurídico' significa que la víctima no tenía el deber de soportar el daño, no que la conducta del Estado fuera ilegal.",
    },
    {
      pregunta: "¿Qué recurso corrige errores de derecho sin volver a juzgar los hechos de un caso?",
      opciones: ["La apelación", "La casación", "La tutela", "El derecho de petición"],
      correcta: 1,
      explicacion: "La casación es un recurso extraordinario centrado en errores jurídicos graves, no en revisar las pruebas de nuevo.",
    },
    {
      pregunta: "¿Qué requiere el reconocimiento de una sentencia extranjera en Colombia (exequátur)?",
      opciones: ["Que la Corte Suprema vuelva a juzgar el fondo del caso", "Verificar requisitos formales como notificación adecuada, orden público y reciprocidad", "Nada, se reconoce automáticamente", "Solo aplica a sentencias penales"],
      correcta: 1,
      explicacion: "El exequátur no revisa el fondo: verifica requisitos formales para dar efectos a la sentencia extranjera en Colombia.",
    },
    {
      pregunta: "¿Qué distingue a la JEP de la justicia penal ordinaria?",
      opciones: ["Solo juzga a civiles", "Prioriza sanciones restaurativas si hay verdad plena, frente a prisión ordinaria si no la hay", "No tiene relación con el conflicto armado", "Reemplaza completamente a la Corte Suprema"],
      correcta: 1,
      explicacion: "Quien reconoce verdad y responsabilidad ante la JEP accede a sanciones propias restaurativas, no prisión ordinaria.",
    },
    {
      pregunta: "¿Qué exige el principio de plena competencia en precios de transferencia?",
      opciones: ["Que las empresas vinculadas paguen el mínimo impuesto posible", "Que las operaciones entre empresas del mismo grupo se pacten como entre partes independientes", "Que solo aplique a empresas extranjeras", "Que no se pueda comerciar entre filiales"],
      correcta: 1,
      explicacion: "Busca evitar que un grupo traslade utilidades artificialmente mediante precios inflados o deflactados entre sus propias empresas.",
    },
  ],
  extra: [
    {
      pregunta: "¿Qué habilita legalmente a un abogado para litigar en Colombia?",
      opciones: ["Solo el diploma universitario", "La tarjeta profesional expedida tras el diploma", "Aprobar un examen tipo 'bar exam'", "Inscribirse en redes sociales como abogado"],
      correcta: 1,
      explicacion: "Colombia no exige un examen de habilitación adicional: el título universitario más la tarjeta profesional son el requisito central.",
    },
    {
      pregunta: "¿Qué es el Saber Pro en la carrera de Derecho?",
      opciones: ["Un examen habilitante para ejercer como abogado", "Una prueba estandarizada obligatoria de pregrado, exigida como requisito de grado en muchas universidades", "Un curso opcional de posgrado", "Un examen solo para quienes quieren ser jueces"],
      correcta: 1,
      explicacion: "El Saber Pro no habilita para ejercer, pero suele ser requisito de grado y se revisa en empleo y posgrados.",
    },
    {
      pregunta: "¿Qué es más determinante en la práctica diaria de un abogado, según la experiencia común?",
      opciones: ["Memorizar códigos completos", "La redacción clara, además del conocimiento técnico", "Tener el promedio más alto de la clase", "Trabajar en la firma más grande posible"],
      correcta: 1,
      explicacion: "Un abogado puede conocer bien el derecho y aun así perder un caso por una redacción confusa o mal estructurada.",
    },
    {
      pregunta: "¿Por qué nunca debes citar en un escrito jurisprudencia generada por una IA sin verificarla?",
      opciones: ["Porque siempre está desactualizada", "Porque estas herramientas pueden generar citas que parecen reales pero no existen", "Porque es ilegal usar IA en derecho", "No hay ningún riesgo real"],
      correcta: 1,
      explicacion: "Ya hay casos documentados de abogados sancionados por citar jurisprudencia inexistente generada por IA sin verificarla.",
    },
    {
      pregunta: "¿De dónde suelen llegar los primeros clientes de una firma nueva?",
      opciones: ["De publicidad paga desde el primer día", "De la red personal y profesional existente del abogado", "Del gobierno automáticamente", "No es posible conseguir clientes al iniciar"],
      correcta: 1,
      explicacion: "Casi siempre llegan por referidos de la red existente, por eso cultivarla desde antes de independizarte es clave.",
    },
  ],
};
